### ISSUE TITLE
Google Drive - Viewers cannot download

### ISSUE THREAD

**Issue by thomaslv93** [MorganLevineLab/PC-Clocks#3]
![viewerscannotdownload](https://user-images.githubusercontent.com/887860/148609868-aea81eae-b612-4662-a7e0-852f0cff1a0d.png)

Cool project! Would love to explore the code with the data provided.

**Comment by kthrush** [comment]
We believe the data should be downloadable now using updated links from the readme or the wiki (now downloading from Box instead of Google Drive). Thank you for bringing this to our attention, and please let us know if you still encounter issues!
I will also put the main link you will need here (https://yale.box.com/s/kq0b0a7lxckxjvaz7x5n4keaug7tewry)

**Comment by thomaslv93** [comment]
Awesome, thank you very much!
